version: '2'
services:
  dnskey:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DNSKEY_DEBUG=0
      - DNSKEY_DATABASE_PRIMARY_LIST=postgresql://dnskey:dnskey123@10.1.7.110:65432/dnskey
      - DNSKEY_DATABASE_REPLICA_LIST=postgresql://dnskey:dnskey123@10.1.7.110:65432/dnskey
      - DNSKEY_MEMCACACHE_SERVERS=10.1.50.51:11211,10.1.50.52:11211,10.1.50.53:11211
      - DNSKEY_HTTP_ALLOWED_HOSTS=*
      - DNSKEY_SERVER_WORKER_PROCESSES=4
      - DNSKEY_RECORD_RECENT_QUERY_TIMES_TIMEOUT=900
      - DNSKEY_EMAIL_USE_TLS=1
      - DNSKEY_EMAIL_USE_SSL=0
      - DNSKEY_EMAIL_HOST=mail.zhumengyuan.com
      - DNSKEY_EMAIL_PORT=587
      - DNSKEY_EMAIL_TIMEOUT=9
      - DNSKEY_EMAIL_HOST_USER=robot@zhumengyuan.com
      - DNSKEY_EMAIL_HOST_PASSWORD='roboto091!@#'
      - DNSKEY_DEFAULT_FROM_EMAIL=robot@zhumengyuan.com
      - DNSKEY_EMAIL_SUBJECT_PREFIX=[DNSKEY]
      - DNSKEY_EMAIL_INTERVAL=300
    ports:
     - 53:53
     - 53:53/udp
     - 17000:17000
    restart: always
    container_name: dnskey
